In [1]:
s = "Hi there Felsy!"
s.split()

['Hi', 'there', 'Felsy!']

In [3]:
planet = "Earth"
diameter = 12742
planet = "Earth"
diameter = 12742
print('The diameter of {} is {} kilometers.'.format(planet,diameter));

The diameter of Earth is 12742 kilometers.


In [4]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print(d['k1'][3]["tricky"][3]['target'][3])

hello


In [7]:
import numpy as np
array=np.zeros(10)
array


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
import numpy as np
array=np.ones(10)*5
array

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [9]:
import numpy as np
array=np.arange(20,35,2)
array

array([20, 22, 24, 26, 28, 30, 32, 34])

In [10]:
matrix=np.arange(0,9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [17]:
import numpy as np
a = np.array([1, 2, 3]) 
b = np.array([4, 5, 6])
ab=np.concatenate((a,b),axis=0)
ab

array([1, 2, 3, 4, 5, 6])

In [19]:
import pandas as pd
data = [['Madhesh', 55], ['Nivedhan', 30], ['Vignesh', 31]]
df = pd.DataFrame(data, columns=['Name', 'Age'])
df

Name  Age
0   Madhesh   55
1  Nivedhan   30
2   Vignesh   31

In [20]:
hariharan = pd.date_range(start ='01-01-2023', 
         end ='02-10-2023' )
  
for val in hariharan:
  print(val)

2023-01-01 00:00:00
2023-01-02 00:00:00
2023-01-03 00:00:00
2023-01-04 00:00:00
2023-01-05 00:00:00
2023-01-06 00:00:00
2023-01-07 00:00:00
2023-01-08 00:00:00
2023-01-09 00:00:00
2023-01-10 00:00:00
2023-01-11 00:00:00
2023-01-12 00:00:00
2023-01-13 00:00:00
2023-01-14 00:00:00
2023-01-15 00:00:00
2023-01-16 00:00:00
2023-01-17 00:00:00
2023-01-18 00:00:00
2023-01-19 00:00:00
2023-01-20 00:00:00
2023-01-21 00:00:00
2023-01-22 00:00:00
2023-01-23 00:00:00
2023-01-24 00:00:00
2023-01-25 00:00:00
2023-01-26 00:00:00
2023-01-27 00:00:00
2023-01-28 00:00:00
2023-01-29 00:00:00
2023-01-30 00:00:00
2023-01-31 00:00:00
2023-02-01 00:00:00
2023-02-02 00:00:00
2023-02-03 00:00:00
2023-02-04 00:00:00
2023-02-05 00:00:00
2023-02-06 00:00:00
2023-02-07 00:00:00
2023-02-08 00:00:00
2023-02-09 00:00:00
2023-02-10 00:00:00


In [23]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
lists = [[1,'aaa', 22], [2,'bbb', 25], [3,'ccc', 24]]
# Create the pandas DataFrame
df = pd.DataFrame(lists, columns = ['s.no','name','Age'])
 
# print dataframe.
print(df )

   s.no name  Age
0     1  aaa   22
1     2  bbb   25
2     3  ccc   24
